server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    gateway:
      routes:

        - id: auth-service
          uri: lb://AUTH
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 20

        - id: admin-auth-service
          uri: lb://AUTH
          predicates:
            - Path=/api/v1/admin/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 20

        - id: user-service
          uri: lb://USER
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 20

        - id: admin-user-service
          uri: lb://USER
          predicates:
            - Path=/api/v1/admin/users/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 20

        - id: vehicle-service
          uri: lb://VEHICLE
          predicates:
            - Path=/api/v1/vehicles/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 20

        - id: station-vehicle-service
          uri: lb://VEHICLE
          predicates:
            - Path=/api/v1/station/vehicles/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 20

        - id: payment-service
          uri: lb://PAYMENT
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 20

        - id: transaction-service
          uri: lb://TRANSACTION
          predicates:
            - Path=/api/v1/transactions/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 20

        - id: admin-transaction-service
          uri: lb://TRANSACTION
          predicates:
            - Path=/api/v1/admin/transactions/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 20


        - id: fuel-session-service
          uri: lb://FUEL-SESSION
          predicates:
            - Path=/api/v1/fuel-sessions/**

        - id: station-service
          uri: lb://STATION
          predicates:
            - Path=/api/v1/stations/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 20

        - id: admin-station-service
          uri: lb://STATION
          predicates:
            - Path=/api/v1/admin/stations/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 20

        - id: admin-pump-device-service
          uri: lb://STATION
          predicates:
            - Path=/api/v1/admin/pump-devices/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 20

        - id: admin-vehicle-service
          uri: lb://VEHICLE
          predicates:
            - Path=/api/v1/admin/vehicles/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 20

        - id: dashboard-service
          uri: lb://DASHBOARD
          predicates:
            - Path=/api/v1/dashboard/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 20


        - id: admin-dashboard-service
          uri: lb://DASHBOARD
          predicates:
            - Path=/api/v1/admin/dashboard/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 20